create table api_token (id varchar(255) not null, created_at bigint not null, delete_time bigint, deleted BOOLEAN DEFAULT FALSE not null, last_used bigint, name varchar(255) not null, owner varchar(255) not null, primary key (id));
create table bin_file (id bigint not null auto_increment, cover bit not null, data_id varchar(255) not null, mime varchar(255) not null, name varchar(255) not null, size bigint not null, ts_create bigint not null, primary key (id));
create table dataset (id varchar(255) not null, delete_time bigint, deleted BOOLEAN DEFAULT FALSE not null, name varchar(255) not null, owner_id varchar(255) not null, short_description varchar(128), timestamp bigint not null, primary key (id));
create table dataset_image (dataset_id varchar(255) not null, image_id varchar(255) not null, primary key (dataset_id, image_id));
create table image (type varchar(31) not null, id varchar(255) not null, delete_time bigint, deleted BOOLEAN DEFAULT FALSE not null, image_name varchar(255) not null, image_type varchar(255) not null, timestamp bigint not null, height integer, width integer, image_url varchar(1256), fk_bin_file_id bigint, primary key (id));
create table label_configuration (id varchar(255) not null, timestamp bigint not null, primary key (id));
create table label_iteration (id varchar(255) not null, run integer not null, timestamp bigint not null, primary key (id));
create table label_task (id varchar(255) not null, label_task_state ENUM('BACKLOG','WAITING', 'WAITING_CHANGED', 'IN_PROGRESS', 'SKIPPED', 'COMPLETED', 'REVIEWED') default 'BACKLOG' not null, labeler varchar(255), image_id varchar(255) not null, label_iteration_id varchar(255) not null, project_id varchar(255) not null, primary key (id));
create table lc_entry (entry_type varchar(31) not null, id varchar(255) not null, entry_key varchar(56) not null, entry_value varchar(56) not null, timestamp bigint not null, type ENUM('POINT', 'LINE', 'POLYGON', 'RECTANGLE', 'SELECT', 'RADIO', 'CHECKLIST', 'FREETEXT') default 'FREETEXT' not null, is_required boolean default false, max_length integer, color varchar(255), shortcut varchar(255), label_config_id varchar(255) not null, parentEntry_id varchar(255), primary key (id));
create table lc_entry_check_list_options (lc_entry_check_list_id varchar(255) not null, lc_entry_check_list_value varchar(255), lc_entry_check_list_key varchar(255) not null, primary key (lc_entry_check_list_id, lc_entry_check_list_key));
create table lc_entry_checklist_values (checklist_value_id varchar(255) not null, checked_value varchar(255));
create table lc_entry_radio_options (lc_entry_radio_id varchar(255) not null, lc_entry_radio_value varchar(255), lc_entry_radio_key varchar(255) not null, primary key (lc_entry_radio_id, lc_entry_radio_key));
create table lc_entry_select_options (lc_entry_select_id varchar(255) not null, lc_entry_select_value varchar(255), lc_entry_select_key varchar(255) not null, primary key (lc_entry_select_id, lc_entry_select_key));
create table lc_entry_value (entry_values_type varchar(31) not null, id varchar(255) not null, labeler varchar(255) not null, timestamp bigint not null, is_valid boolean default false, radio_key varchar(255), select_key varchar(255), text varchar(255), x double precision, y double precision, height double precision, width double precision, image_id varchar(255) not null, label_iteration_id varchar(255) not null, lc_entry_id varchar(255) not null, lcEntryValueParent_Id varchar(255), primary key (id));
create table limits (id varchar(255) not null, ai_seg_limit integer not null, ai_seg_remaining integer not null, api_access bit not null, pricing_plan_type ENUM('FREE_DEVELOPER','DEVELOPER_PRO', 'TEAM_PRO') default 'FREE_DEVELOPER' not null, external_storage bit not null, label_limit integer not null, label_remaining integer not null, last_reset bigint, organisation_id varchar(255) not null, project_limit integer not null, project_used integer not null, storage_limit bigint not null, storage_used bigint not null, timestamp bigint not null, primary key (id));
create table point_pojo (id varchar(255) not null, x double precision, y double precision, line_value_id varchar(255), polygon_value_id varchar(255), point_uuid integer, primary key (id));
create table project (id varchar(255) not null, delete_time bigint, deleted BOOLEAN DEFAULT FALSE not null, description varchar(1024), name varchar(255) not null, owner_id varchar(255) not null, pinned BOOLEAN DEFAULT FALSE not null, short_description varchar(128) not null, timestamp bigint not null, label_configuration_id varchar(255), label_iteration_id varchar(255), primary key (id));
create table project_dataset (project_id varchar(255) not null, dataset_id varchar(255) not null, primary key (project_id, dataset_id));
alter table dataset_image add constraint fk_image_dataset foreign key (image_id) references image (id);
alter table dataset_image add constraint fk_dataset_image foreign key (dataset_id) references dataset (id);
alter table image add constraint fk_localimage_binfileentity foreign key (fk_bin_file_id) references bin_file (id);
alter table label_task add constraint fk_labeltask_image foreign key (image_id) references image (id);
alter table label_task add constraint fk_labeltask_labeliteration foreign key (label_iteration_id) references label_iteration (id);
alter table label_task add constraint fk_labeltask_project foreign key (project_id) references project (id);
alter table lc_entry add constraint fk_lcentry_labelconfiguration foreign key (label_config_id) references label_configuration (id);
alter table lc_entry add constraint fk_lcentry_lcentryparent foreign key (parentEntry_id) references lc_entry (id);
alter table lc_entry_check_list_options add constraint fk_checklistoptions_checklist foreign key (lc_entry_check_list_id) references lc_entry (id);
alter table lc_entry_checklist_values add constraint fk_checklistvalues_checklistvalue foreign key (checklist_value_id) references lc_entry_value (id);
alter table lc_entry_radio_options add constraint fk_radiooptions_radio foreign key (lc_entry_radio_id) references lc_entry (id);
alter table lc_entry_select_options add constraint fk_selectoptions_select foreign key (lc_entry_select_id) references lc_entry (id);
alter table lc_entry_value add constraint fk_entryvalue_image foreign key (image_id) references image (id);
alter table lc_entry_value add constraint fk_entryvalue_labeliteration foreign key (label_iteration_id) references label_iteration (id);
alter table lc_entry_value add constraint fk_entryvalue_lcentrychildren foreign key (lc_entry_id) references lc_entry (id);
alter table lc_entry_value add constraint fk_entryvalue_lcentryparent foreign key (lcEntryValueParent_Id) references lc_entry_value (id);
alter table point_pojo add constraint fk_pointpojo_entryvalueline foreign key (line_value_id) references lc_entry_value (id);
alter table point_pojo add constraint fk_pointpojo_entryvaluepoly foreign key (polygon_value_id) references lc_entry_value (id);
alter table project add constraint fk_project_labelconfiguration foreign key (label_configuration_id) references label_configuration (id);
alter table project add constraint fk_project_labeliteration foreign key (label_iteration_id) references label_iteration (id);
alter table project_dataset add constraint fk_dataset_project foreign key (dataset_id) references dataset (id);
alter table project_dataset add constraint fk_project_dataset foreign key (project_id) references project (id);